export const REGISTRATION = "REGISTRATION"
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";

export const MODAL = "MODAL";

export const AUTHORIZATION = "AUTHORIZATION"
export const AUTHORIZATION_SUCCESS = "AUTHORIZATION_SUCCESS"
export const AUTHORIZATION_FAILED = "AUTHORIZATION_FAILED"
export const AUTHORIZATION_VISIT = "AUTHORIZATION_VISIT"

export const LOGOUT = "LOGOUT"

export const OPEN_ALERT = "OPEN_ALERT"
export const CLOSE_ALERT = "CLOSE_ALERT"

export const PROFILE_LOAD = "PROFILE_LOAD"
export const PROFILE_LOAD_SUCCESS = "PROFILE_LOAD_SUCCESS"
export const PROFILE_LOAD_FAILED = "PROFILE_LOAD_FAILED"

export const EDIT_PROFILE = "EDIT_PROFILE";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAILED = "EDIT_PROFILE_FAILED";

export const ADD_DISEASE = "ADD_DISEASE";
export const ADD_DISEASE_SUCCESS = "ADD_DISEASE_SUCCESS";
export const ADD_DISEASE_FAILED = "ADD_DISEASE_FAILDER"